credentials/urls.py
from django.urls import path
from . import views

app_name = 'credential'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('sign-out/', views.signout, name="sign-out"),
    path('user_det/<int:u_id>/', views.user_det, name="user_detail")
]

mov_fun/urls.py
from django.urls import path
from . import views


app_name = 'add_'

urlpatterns = [
    path('add_movie/', views.add, name="add_mov"),
    path('update/<int:up_id>/', views.update, name="update"),
    path('delete/<int:del_id>/', views.delete, name="delete"),
]

movworld/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movworldapp.urls')),
    path('credentials/', include('credentials.urls')),
    path('mov_fun/', include('mov_fun.urls')),
    path('search/', include('searchapp.urls')),
    path('review/', include('reviewapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movworldapp/urls.py
from django.urls import path
from . import views

app_name = 'mov_wo'

urlpatterns = [
    path('', views.home, name="home"),
    path('<int:c_id>/', views.home, name="mov_by_cat"),
    path('<int:c_id>/<int:m_id>/', views.detail, name="mov_detail"),

]

reviewapp/urls.py
from django.urls import path
from . import views

app_name = 'rev_rate'

urlpatterns = [
    path('movie/<slug:m_slug>/', views.movie_det, name="movie_details_fun"),
]

searchapp/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.search, name="search"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet"  href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/my.css' %}">
    <script src="https://kit.fontawesome.com/e9136e1d96.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<div class="container">
    {% include 'navbar.html' %}
    {% block body %}
    {% endblock %}
</div>

{% include 'footer.html' %}

<script src="{% static 'assets/js/slim.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Delete
{% endblock %}
{% block title %}
Delete
{% endblock %}
{% block body %}
<div class="main-w3layouts wrapper" >
		<div class="main-agileinfo">
			<div class="agileits-top">


    <ul class="messages">
        {% for message in messages %}
            <p style="padding-top:30px;font-weight:bold;color:#fff;">{{message}}</p>
        {% endfor %}
        <a class="btn btn-light" href="{% url 'mov_wo:home' %}">Go back</a>
    </ul>

            </div>
        </div>
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Movie Details
{% endblock %}
{% block title %}
MovieDetail
{% endblock %}
{% block body %}


<div class="container" style="padding-top:40px;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 mt-5">
            <div class="card bg-dark" style="min-width:30rem;color:#fff;width:200px;box-shadow: 3px 4px 5px #000;align:center;">
                <img class="card-img-top my-image" style="padding-top:15px;" height="300px" src="{{mov_det.poster.url}}" alt="{{mov_det.title}}"></a>
                <div class="card-body">
                    <p style="font-size:20px;font-weight:bold;">{{mov_det.title}}</p>
                    <h3>{{mov_det.release_date}}</h3>
                    <h3>{{mov_det.category}}</h3><br>
                    <p>{{mov_det.desc}}</p>
                <center><a href="{% url 'add_:update' mov_det.id %}" class="btn btn-light mt-3">Update</a></center>
                    <center><a href="{% url 'add_:delete' mov_det.id %}" class="btn btn-light mt-3">Delete</a></center>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 mt-5">
                         <span class="heading" style="color:#fff;">User Reviews and Ratings</span>
<span class="fa fa-star checked" style="color:#fff;"></span>
<span class="fa fa-star checked" style="color:#fff;"></span>
<span class="fa fa-star checked" style="color:#fff;"></span>
<span class="fa fa-star checked" style="color:#fff;"></span>
<span class="fa fa-star" style="color:#fff;"></span>
<p></p>
<hr style="border:3px solid #fff">
            {% for review in rev %}
            <div class="shadow card">
                <div class="card-body" style="color:#fff;">
                    <div class="card-title">Rating: {{ review.rating}}</div>
                    <h3>Review: {{ review.comment }}</h3>
                    <p>Reviewed by: {{review.user}} | {{review.movie}}</p>
                </div>
            </div>
            {% endfor %}
     </div>
    </div>
</div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% block metadescription %}
error
{% endblock %}
{% block title %}
Error
{% endblock %}
{% block body %}
<div class="main-w3layouts wrapper" >
		<div class="main-agileinfo">
			<div class="agileits-top">


    <ul class="messages">
        {% for message in messages %}
            <p style="padding-top:30px;font-weight:bold;color:#fff;">{{message}}</p>
        {% endfor %}
        <a class="btn btn-light" href="{% url 'mov_wo:home' %}">Go back</a>
    </ul>

            </div>
        </div>
</div>
{% endblock %}

templates/footer.html
	<div class="colorlibcopy-agile">
			<p style="font-weight:bold;padding-bottom:1px;">© 2024 Movworld Signup Form. All rights reserved | Design by <a href="https://movworld.com/" target="_blank">movworld</a></p>
		</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if mov_cat %}
{{mov_cat.desc|truncatewords:155}}
{% else %}
Welcome to MovWorld
{% endif %}
{% endblock %}
{% block title %}
{% if mov_cat %}
{{mov_cat.name}}
{% else %}
MovWorld
{% endif %}
{% endblock %}
{% block body %}



{% if mov_cat %}
<div class="container">
    <div class="row">
  <div class="col-12">
      <div style="color:#fff;padding-top:100px;">
    <div class="card">

      <div class="card-body">
        <h1 class="card-title">{{mov_cat.category}}</h1>
          <img src="{{mov_cat.img.url}}" width="180" height="220" class="card-img-bottom" alt="{{mov_cat.category}}">
        <p class="card-text">{{mov_cat.desc}}</p>
      </div>
    </div>
  </div>
      </div>

</div>

<div class="container" style="">
    <div class="row">
        {% for i in mov_list %}
        <div class="col-12 col-sm-12 col-md-12 col-lg-3 mt-5">
            <div class="card bg-dark" style="min-width:12rem;color:#fff;width:200px;box-shadow: 3px 4px 5px #000;align:center;">
                <a href="{{i.get_url}}"><img class="card-img-top my-image" style="padding-top:15px;" height="200px" src="{{i.poster.url}}" alt="{{i.title}}"></a>
                <div class="card-body">
                    <p style="font-size:20px;font-weight:bold;">{{i.title}}</p>
                    <h3>{{i.release_date}}</h3>
                    <p>{{i.category}}</p><br>

<!--                <center><a href="{% url 'add_:update' i.id %}" class="btn btn-light mt-3">Update</a></center>-->
<!--                    <center><a href="{% url 'add_:delete' i.id %}" class="btn btn-light mt-3">Delete</a></center>-->

                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% else %}
<div class="container" >

    <div class="row mx-auto">
        <div class="col-md-12">
            <div style="color:#fff;padding-top:80px;">
            <br>
                			{% if messages %}
    <div class="alert alert-danger">
		{% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
                <center><h1 style="color:#fff;padding-top:40px;font-weight:bold;font-size:30px;">.Movies To Explore.</h1></center>
            <div style="color:light;padding-top:10px;font-size:15px;">

                <p>The Mov World Review WebApp simple yet efficient platform for movie enthusiasts. It provides a one-stop solution for all your movie reviews and ratings needs. With its user-generated content and easy navigation, the app stands out!!! So, the next time you are in a dilemma about what movie to watch, give Mov World Review App a try, and you won’t be disappointed.</p>
            </div>
            </div>
    </div>
</div>

<div class="container">
    <div class="row mx-auto m-3" style="">
        {% for i in mov.object_list %}
        <div class="row col-9 col-sm-12 col-md-12 col-lg-2 m-3">
            <div class="card bg-dark" style="min-width:12rem;color:#fff;width:200px;box-shadow: 3px 4px 5px #000;align:center;">
                <img class="card-img-top my-image" style="padding-top:15px;" height="200px" src="{{i.poster.url}}" alt="{{i.title}}">
                <div class="card-body">
                    <center><p style="font-size:20px;font-weight:bold;">{{i.title}}</p>
                    <p>{{i.release_date}}</p>
                        <p>{{i.category}}</p></center>
                                        <center><a href="{% url 'rev_rate:movie_details_fun' i.m_slug %}" class="btn btn-light mt-1">Add Review</a></center>

<!--                <center><a href="{% url 'add_:update' i.id %}" class="btn btn-light mt-3">Update</a></center>-->
<!--                    <center><a href="{% url 'add_:delete' i.id %}" class="btn btn-light mt-3">Delete</a></center>-->

                </div>
            </div>
        </div>
        {% endfor %}

        </div>
    </div>
</div>
    {% endif %}
   <div class="mx-auto">
        {% if mov.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in mov.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if mov.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
        </div>
</div>
{% endblock %}

templates/mov_det_fun.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Movie
{% endblock %}
{% block title %}
MovieDetailsAndFunctions
{% endblock %}
{% block body %}

<div class="container" style="padding-top:80px;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 mt-2">
            <div class="card bg-dark" style="min-width:30rem;color:#fff;width:200px;box-shadow: 3px 4px 5px #000;align:center;">
                <img class="card-img-top my-image" style="padding-top:15px;" height="300px" src="{{mov.poster.url}}" alt="{{mov_det.title}}"></a>
                <div class="card-body">
                    <h3 style="font-size:20px;font-weight:bold;">{{mov.title}}</h3>
                    <p>{{mov.release_date}} || {{mov.category}}</p>
                    <p>{{mov.desc}}</p>
                <center><a href="{% url 'add_:update' mov.id %}" class="btn btn-light mt-3">Update</a></center>
                    <center><a href="{% url 'add_:delete' mov.id %}" class="btn btn-light mt-3">Delete</a></center>
                  <form method="post" action="">
                {% csrf_token %}
                <label><b>Rate:</b></label><br>
                <input type="number" name="rating" min="0" max="5" step="1"><br>
                <label for="review"><b>Review:</b></label><br>
                <textarea id="review" name="comment" rows="5" cols="50" placeholder="Comment here..."></textarea>

                <br>
                <input type="submit" value="Submit">
            </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 mt-3">
                   <span class="heading" style="color:#fff;font-weight:bold;">User Reviews and Ratings</span>
<span class="fa fa-star checked" style="color:#ffff;"></span>
<span class="fa fa-star checked" style="color:#ffff;"></span>
<span class="fa fa-star checked" style="color:#ffff;"></span>
<span class="fa fa-star checked" style="color:#ffff;"></span>
<span class="fa fa-star" style="color:#ffff;"></span>
<p></p>
<hr style="border:3px solid #fffff">
            {% for review in mov.review_set.all %}
            <div class="shadow card">
                <div class="card-body" style="background-color:#000;color:#fff;">
                    <div class="card-title"><p style="font-size:15px;">Rating: {{ review.rating}}</p></div>
                    <p style="font-size:20px;">{{ review.comment }}</p>
                    <p style="font-size:12px;padding-top:10px;">Reviewed by: {{review.user}} | {{review.movie}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-scroll fixed-top shadow-0 border-bottom border-dark navy">
  <div class="container">
    <a class="navbar-brand" style="color:black;font-size:30px;font-weight:bold;" href="{% url 'mov_wo:home'%}"><b>MOVWORLD</b></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
          <li class="nav-item li_nav">
     <form class="d-flex" action="{% url 'search_app:search' %}" method="get">
      {% csrf_token %}
        <input class="form-control mr-sm-2 nav-item" type="search" autocomplete="off"  name="q" aria-label="Search" required style="background-color:#000;opacity:.5;border: 3px solid #ff4c17;color:white;width:400px;">
      <button  class="btn btn-outline-dark my-2 my-sm-0 " style="border: 3px solid #ff4c17;background-color: #000;" type="submit" ><i class="fa-solid fa-magnifying-glass" style="color:#ff4c17;"></i></button>
    </form>
          </li>


        <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" style="color:#000000;">Category</a>
    <ul class="dropdown-menu" style="background-color:#000;">
        {% for cat in links %}
      <li><a class="dropdown-item" style="color:#ff4c17;" href="{{cat.get_url}}">{{cat.category}}</a></li>
        {% endfor %}
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" style="color:#ff4c17;" href="{% url 'mov_wo:home' %}">All movies</a></li>
    </ul>
  </li>


        <li class="nav-item" >
          <a class="nav-link" href="{% url 'add_:add_mov' %}">AddMovies</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credential:user_detail' user.id %}">{{user.username}}</a>
        </li>
                <a href="{% url 'credential:sign-out' %}"><button type="button" class="btn btn-dark ms-3 btn-signup" style="letter-spacing:.2em;color:#ff4c17;"><b>SignOut</b></button></a>
            {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'credential:signin' %}">SignIn</a>
        </li>
        <a href="{% url 'credential:signup' %}"><button type="button" class="btn btn-dark ms-3 btn-signup" style="color:#ff4c17;letter-spacing:.2em;"><b>SignUp</b></button></a>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

<!--Searchbar-->

<!--Searchbar-->

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Search Result
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block body %}
<div class="container" style="padding-top:100px;">
    <div class="text-center my-search" style="font-weight:bold;color:#fff;">You have searched for <b>"{{query}}"</b></div>
</div>
<div class="container" style="padding-top:40px;">
    <div class="row mx-auto">
        {% for mov in movie %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-6 col-lg-4">
            <div class="card text-center">
                <a href="{% url 'rev_rate:movie_details_fun' mov.m_slug %}"><img class="card-img-top my-image" src="{{mov.poster.url}}" width="300" height="300" alt="{{mov.name}}"></a>
                <div class="card-body">
                    <div class="my-title" style="color:#fff;">
                        <h6>{{mov.title}}</h6>
                        <p>{{mov.category}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
        {% empty %}
    <div class="row mx-auto">
        <h1 class="text-center my-search" style="font-weight:bold;color:#fff;padding-top:100px;">
            0 Results Found.</h1>
        <p class="text-center my-search" style="font-size:15px;font-weight:bold;color:#fff;"><a style="color:#fff;" href="{% url 'mov_wo:home' %}">Click here to go back...</a></p>

    </div>

    {% endfor %}
</div>


{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Here You're Login with your username and password.
{% endblock %}
{% block title %}
SignIn
{% endblock %}
{% block body %}
<div class="container signin_con mt-5" style="color:#fff;">
<form class="login-form" method="post" action="">
  {% csrf_token %}
  <p class="login-text">
    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-lock fa-stack-1x"></i>
    </span>
  </p>
  <input type="text" class="login-username input-in" autofocus="autofocus" required="required" placeholder="Username" name="username" />
  <input type="password" class="login-password input-in" required="required" placeholder="Password" name="password"/>
<!--  <input type="submit" name="Login" value="Login" class="login-submit input-in"  />-->
  <button type="submit" name="Login" value="Login" class="login-submit input-in">SignIn</button>
</form>
	{% if messages %}
    <div class="alert alert-light">
		{% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<a href="{% url 'credential:signup' %}" class="login-forgot-pass">Don't have an account? signup here!!!</a>
<div class="underlay-photo"></div>
<div class="underlay-black"></div>
</div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{%  block metadescription %}Register Your name and details to get in.{% endblock %}
{% block title %}SignUp{% endblock %}
{% block body %}
	<!-- main -->
	<div class="main-w3layouts wrapper" >
		<h1 style="padding-top:50px;font-weight:bold;">SignUp</h1>
			{% if messages %}
    <div class="alert alert-danger">
		{% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="" method="post">
					{% csrf_token %}
					<input class="text" type="text" name="userName" placeholder="Username" required="" autocomplete="off"><br>
					<input class="text" type="text" name="firstName" placeholder="Firstname" required="" autocomplete="off"><br>
					<input class="text" type="text" name="lastName" placeholder="Lastname" required="" autocomplete="off">
					<input class="text email" type="email" name="email" placeholder="Email" required="" autocomplete="off">
					<input class="text" type="password" name="psw" placeholder="Password" required="">
					<input class="text w3lpass" type="password" name="psw-repeat" placeholder="Confirm Password" required="">
					<div class="wthree-text">
						<label class="anim">

							<span><b>I Agree To The <a href="#">Terms & Conditions</a></b></span>
						</label>
						<div class="clear"> </div>
					</div>
					<input type="submit" value="SIGNUP">
				</form>

				<!-- Inside your template -->

				<p>have an Account? <a href="{% url 'credential:signin' %}"> Signin Now!</a></p>
			</div>
		</div>

		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if user.is_authenticated  %}
{{user.username}} you can update movies here.
{% else %}
You have to log in first to update movies here.
{% endif %}
{% endblock %}
{% block title %}
UpdateMovies
{% endblock %}
{% block body %}
<div class="main-w3layouts wrapper" >
		<h1 style="padding-top:30px;font-weight:bold;">Upadte Movies</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
            <form action="" method="post" enctype="multipart/form-data" style="text-align: center;display: inline-block;color:#fff;padding-top:5px;">
                {% csrf_token %}
                <div class="form-group">
                   {{mov_fo.as_ul}}
                <br><button type="submit">Submit</button>
                </div>
            </form>

                 <ul class="messages">
        {% for message in messages %}
            <p style="padding-top:30px;font-weight:bold;color:#fff;">{{message}}</p>
        {% endfor %}
        <a class="btn btn-light" href="{% url 'mov_wo:home' %}">Go back</a>
    </ul>
        </div>
    </div>
</div>
<div class="col-4"></div>
{% endblock %}

templates/user_det.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Mov
{% endblock %}
{% block title %}
Mov
{% endblock %}
{% block body %}

<div class="container" style="padding-top:80px;align:center;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 mt-5">
             <div class="shadow card">
                <div class="card-body">
                    <div class="card-title" style="color:#fff;"><b>Username:</b> {{user.username}}</div><br>
                    <p style="color:#fff;"><b>Firstname:</b> {{user.first_name}}</p><br>
                    <p style="color:#fff;"><b>Lastname:</b> {{user.last_name}}</p><br>
                    <p style="color:#fff;"><b>Email:</b> {{user.email}}</p><br>
                    <a class="btn btn-dark" href="{% url 'mov_wo:home' %}">Go back</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}